### ISSUE TITLE
Custom icons

### ISSUE THREAD

**Issue by mt633** [Jamalianpour/easy_sidemenu#1]
This project looks great! I was just wondering if you are planning on adding an option to support custom icons (i.e. add a `Widget` instead of `IconData`). That would allow the user to use, for instance, [badges](https://pub.dev/packages/badges) for icons instead.

**Comment by Jamalianpour** [comment]
Hello, thank you for your recommendation
I will do this in the next version

**Comment by mt633** [comment]
Brilliant, thanks. I look forward to the next version!

**Comment by Jamalianpour** [comment]
Hi,
For some reason in new version (0.2.0) `IconData` is replaced with `Icon`.
But now you can add badge to the icons with `badgeContent`

**Comment by mt633** [comment]
Great, thanks!
