### ISSUE TITLE
Is it possible to add listener when SideMenuDisplayMode changes

### ISSUE THREAD

**Issue by jordandevogelaere** [Jamalianpour/easy_sidemenu#10]
Hi,

I want to know if its possible to add listener to the SideMenu that triggers when the SideMenuDisplayMode changes.

F.E. I want to change the footer widget when the SideMenu goes from `open` to `compact` 

Thanks in advance. 

Kind regards,
Jordan de Vogelaere

**Comment by Jamalianpour** [comment]
Hello @jordandevogelaere,

In the current version this is impossible, But a new version will be released soon and you can do it easily.

But I have to say that the footer widget is only shown in open `mode`

**Comment by Jamalianpour** [comment]
Hello @jordandevogelaere,
Now you can use new version (0.3.0) and use  `onDisplayModeChanged`.

```dart
SideMenu(
  controller: page,
  onDisplayModeChanged: (mode) {
    print(mode);
  },
  items: items,
),
```

Have fun and star this repo if you like it.
