### ISSUE TITLE
Don't create icon image from asset 

### ISSUE THREAD

**Issue by khoitqa** [Jamalianpour/easy_sidemenu#12]
Why I don't add ImageIcon in the icon of SideMenuItem? What happen when I want to use my icon which doesn't exist in Google's Icon Warehouse?

**Comment by Jamalianpour** [comment]
Hello @anhkhoi159,
You can create your own custom icons and use them as `IconData`
https://medium.com/codechai/how-to-use-custom-icons-in-flutter-834a079d977

**Comment by khoitqa** [comment]
> https://medium.com/codechai/how-to-use-custom-icons-in-flutter-834a079d977
It's worked, thanks sm
