### ISSUE TITLE
Toggle Button Icon Position Header and Footer

### ISSUE THREAD

**Issue by Cratis1831** [Jamalianpour/easy_sidemenu#14]
Would it be possible to have a flag that lets you move the toggle button to the bottom of the side bar instead of the top?

Also if you can change the icon as well

right now it sits over the first element of the side menu when in open mode, would be a nice feature
![Untitled](https://user-images.githubusercontent.com/1056561/176430331-c8fcf609-be1c-428f-8eef-d4e07638d3a4.png)

**Comment by Jamalianpour** [comment]
Hello @Cratis1831,
This is not currently possible, but you can create your own toggle button and use it wherever you want.

https://github.com/Jamalianpour/easy_sidemenu/issues/7#issuecomment-1094344230

**Comment by Cratis1831** [comment]
Hey @Jamalianpour 
Thanks got it working to not overlap! I actually kept it at the top still

![Untitled](https://user-images.githubusercontent.com/1056561/176467927-888a40c0-51a5-4d27-9b1f-9b2d5a006312.png)

**Comment by SteveBraich** [comment]
> Hey @Jamalianpour Thanks got it working to not overlap! I actually kept it at the top still
> 
> ![Untitled](https://user-images.githubusercontent.com/1056561/176467927-888a40c0-51a5-4d27-9b1f-9b2d5a006312.png)

That's awesome!  Would you mind sharing how you did it?

**Comment by Cratis1831** [comment]
> > Hey @Jamalianpour Thanks got it working to not overlap! I actually kept it at the top still
> > ![Untitled](https://user-images.githubusercontent.com/1056561/176467927-888a40c0-51a5-4d27-9b1f-9b2d5a006312.png)
> 
> That's awesome! Would you mind sharing how you did it?



```dart
SideMenu(
            controller: page,
            style: SideMenuStyle(
                displayMode: displayMode,
                hoverColor: Colors.grey[800],
                selectedColor: Colors.grey[800],
                selectedTitleTextStyle: TextStyle(color: Theme.of(context).textTheme.bodyLarge?.color, fontSize: 14),
                selectedIconColor: Colors.red,
                unselectedIconColor: Colors.white,
                unselectedTitleTextStyle: TextStyle(color: Theme.of(context).textTheme.bodyLarge?.color, fontSize: 14),
                toggleColor: Colors.white,
                openSideMenuWidth: 200,
                backgroundColor: const Color.fromARGB(255, 57, 57, 57)),
            title: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              //mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: [
                ConstrainedBox(
                  constraints: const BoxConstraints(
                    maxHeight: 150,
                    maxWidth: 150,
                  ),
                  // child: Image.asset(
                  //   'assets/images/easy_sidemenu.png',
                  // ),
                  child: Padding(
                    padding: const EdgeInsets.only(left: 6),
                    child: IconButton(
                      tooltip: "Expand",
                      onPressed: () {
                        setState(() {
                          if (displayMode == SideMenuDisplayMode.open) {
                            displayMode = SideMenuDisplayMode.compact;
                            rotate = 1;
                          } else {
                            displayMode = SideMenuDisplayMode.open;
                            rotate = 90;
                          }
                        });
                      },
                      icon: Transform.rotate(
                        angle: 90 * math.pi / rotate,
                        child: const Icon(
                          Icons.arrow_forward_ios,
                          color: Colors.white,
                          size: 18,
                        ),
                      ),
                    ),
                  ),
                ),
                const Divider(
                  indent: 8.0,
                  endIndent: 8.0,
                ),
              ],
            ),```

**Comment by SteveBraich** [comment]
Thanks for requesting this feature and providing a solution!

**Comment by Cratis1831** [comment]
> Thanks for requesting this feature and providing a solution!

Np! Hopefully my solution helps you, it's been a while since I looked at the code
