### ISSUE TITLE
Bottom Icons

### ISSUE THREAD

**Issue by Cratis1831** [Jamalianpour/easy_sidemenu#16]
Is there a way to also have SideMenuItems in the Footer or at bottom of Side Menu? Something like this?
![menu](https://user-images.githubusercontent.com/1056561/180031542-8353163f-ce30-49b3-88cb-b6d6e19bfc40.png)

**Comment by Jamalianpour** [comment]
Currently it wasn't possible to add SideMenuItems in the footer but you can use any widget in the footer and create your own button.

**Comment by Cratis1831** [comment]
thx @Jamalianpour , is there a way to add widgets when the menu is not open though as footer requires the menu to be opened to display any of the widgets

**Comment by Jamalianpour** [comment]
Unfortunately no,
But I will work on it as soon as possible

**Comment by Cratis1831** [comment]
thank you very much!

**Comment by Jamalianpour** [comment]
@Cratis1831 Now from master branch you can use `alwaysShowFooter` in SideMenu.
If set `alwaysShowFooter` to true always shown footer even display mode is compact.
```dart
SideMenu(
  controller: page,
  alwaysShowFooter: true,
  // ...
),
```

**Comment by Cratis1831** [comment]
@Jamalianpour amazing thank you!!
