### ISSUE TITLE
MouseRegion

### ISSUE THREAD

**Issue by MarceloRab** [Jamalianpour/easy_sidemenu#25]
Could you add a function so that it can show the name when the mouse pointer is over the icon and is in SideMenuDisplay.compact mode?

**Comment by Jamalianpour** [comment]
Hello,
Did you want something like tooltip?

**Comment by MarceloRab** [comment]
When the mouse cursor is over the icon, in SideMenuDisplay.compact mode, I can show the text of the item's title. Like a toast. I can only do this if I use MouseRegion with the onHover function, for example.

**Comment by Jamalianpour** [comment]
In master branch you can use tooltip for this. But currently it wasn't release at pub.dev

To do this use style like:
```dart
style: SideMenuStyle(
  showTooltipOverItemsName: true,
  ...
),
```

and then set value for tooltip:
```dart
items: [
  SideMenuItem(
    priority: 0,
    title: 'Dashboard',
    tooltipContent: "Dashboard",
    ...
  ),
],
```

**Comment by MarceloRab** [comment]
Excellent. I'll try. Grateful.
