### ISSUE TITLE
SideMenu doesn't show when navigation back and forth

### ISSUE THREAD

**Issue by HasanElHefnawy** [Jamalianpour/easy_sidemenu#26]
Suppose you have two pages, Page_A (doesn't have SideMenu) and Page_B (has SideMenu).
Navigate from Page_A to Page_B, SideMenu shows without any problems.
Return from Page_B to Page_A.
Navigate again from Page_A to Page_B, SideMenu doesn't show.
This use case is possible if Page_A is a Login Page.

**Comment by DongPhamBK** [comment]
I still have this problem in the latest version, looks like you removed the solution code for problem #26

**Comment by HasanElHefnawy** [comment]
Yes, I found the same issue shows again in the latest version after it was fixed in version [0.4.0](https://pub.dev/packages/easy_sidemenu/versions/0.4.0). You may want to roll back to the old version until it's fixed again.
