### ISSUE TITLE
Allow custom icons for SideMenuItem

### ISSUE THREAD

**Issue by iamelio** [Jamalianpour/easy_sidemenu#32]
Hi. I was building a complex design for a client a few days ago, and I came across some functionality that I couldn't implement with the in-built Flutter `NavigationRail` so I searched until I stumbled upon this awesome package. It's worked very well to meet all my design requirements so far but now I've hit a roadblock. 

Basically, I need to use SVG images for some icons as there are no equivalent icons available, so I need to use a custom widget but the `icon` property of `SideMenuItem` only accepts an `Icon`.

I'd be happy to make a PR to fix this if you prefer.

**Comment by Jamalianpour** [comment]
@thecokerdavid You can convert your image and svg file to `iconData`.
But at all from version 0.4.1 use builder to create your own custom `sideMenuItem`

**Comment by iamelio** [comment]
Thanks, I already considered both suggestions before creating this issue. I think they are both overkill, since in this case I only need to substitute a few icons for simple SVG widgets, compared to sacrificing readability & development speed by configuring json & ttf files (in the case of custom `iconData`) or having to re-implement some of the package's inbuilt functionality for the special widget (in the case of creating a custom `sideMenuItem`).

**Comment by iamelio** [comment]
I just had a quick look at the code, and I suggest if you prefer not to modify the icon type, you can instead add an optional property that you can call `iconWidget` which will be shown if the `icon` is null, or both can also exist together if you prefer.

I need this urgently so I'd be grateful if it's something you could do soon, or I can implement a PR for that.

**Comment by Jamalianpour** [comment]
Yes that's right,
You are free to open PR and I will be happy

**Comment by iamelio** [comment]
Alright, thanks a bunch! I'll make the PR with the changes in a few minutes.
