### ISSUE TITLE
Error when trying to use builder instead of icon and title.

### ISSUE THREAD

**Issue by felixkriechbaum** [Jamalianpour/easy_sidemenu#39]
When I try to use the builder instead of the icon & title I get following error:

`Exception has occurred.
_AssertionError ('package:easy_sidemenu/src/side_menu_item.dart': Failed assertion: line 25 pos 16: 'title != null || icon != null': Title and icon should not be empty at the same time)`

You wrote on pub.dev/packages/easy_sidemenu

Instead of title **and** icon in SideMenuItem can use builder to create your customize items:
![image](https://user-images.githubusercontent.com/1184644/205510963-6a1a76e2-27fb-4f2b-8756-4f7aa621e5cf.png)

MyCode:
![image](https://user-images.githubusercontent.com/1184644/205510900-2fcdb3b1-336f-461e-bb58-28d5b4b61bf3.png)

**Comment by Jamalianpour** [comment]
Oh sorry you right
It will be fixed in next version
