### ISSUE TITLE
After login receive: Error: setState() called after dispose(): _SideMenuItemState#a4e13(lifecycle state: defunct, not mounted)

### ISSUE THREAD

**Issue by federico2390** [Jamalianpour/easy_sidemenu#45]
Hello after login screen, when push to Home Screen, I receive this error:

Error: setState() called after dispose(): _SideMenuItemState#a4e13(lifecycle state: defunct, not mounted)

How can I fix it?

**Comment by aditya113141** [comment]
Started getting this error randomly. Any follow up on this ?
