### ISSUE TITLE
sidemenucontroller.changepage(int) is not working!

### ISSUE THREAD

**Issue by ysahin20** [Jamalianpour/easy_sidemenu#47]
Hello,

I was having the badge error because of the flutter update then I update the sidemenu to  `easy_sidemenu: ^0.4.1+1`  after that my code give error to change the pagecontroller that ı was using to a side menu controller and SideMenuItem's on tap was changed to 
`final void Function(int, SideMenuController)? onTap;` 

After making those changes my menu stopped working. When I click items, tha page is not changing. 

` onTap: (index, controller) {
        sideMenuController.changePage(index);
      },`

is not working

` onTap: (index, controller) {
        controller.changePage(index);
      },`

is not working as well. 

I would be very happy if you help me.

**Comment by Jamalianpour** [comment]
Hello,

I think you used master branch of repository before update to `easy_sidemenu: ^0.4.1+1`

`SideMenuController` in master had so much issue so I decide to remove that for now, please read readme again

**Comment by ysahin20** [comment]
But I do not know how not to use the master branch. 
Downgrading to `easy_sidemenu: ^0.4.1` did not helped as well.
I am a little confused right now.

**Comment by Jamalianpour** [comment]
`easy_sidemenu` doesn't have `SideMenuController` you should use PageController for that

**Comment by Danny-Rufus** [comment]
I have the same issue.
Using the version `0.4.1` with the flutter version `3.10.0` gives the following error

` Error: 'Badge' is imported from both 'package:badges/src/badge.dart' an
d 'package:flutter/src/material/badge.dart'.
      return Badge(
`
Updating to use the latest version that is `0.4.1+1` throws the following error

` Error: The argument type void Function() can't be assigned to the parameter type void Function(int, SideMenuController)? - SideMenuController is from package:easy_sidemenu/src/global/global.dart`
