### ISSUE TITLE
How to set the Default SideMenuItem?

### ISSUE THREAD

**Issue by SteveBraich** [Jamalianpour/easy_sidemenu#63]
How do I set the Default SideMenuItem?

**Comment by Jamalianpour** [comment]
What are you meaning of Default SideMenuItem?

**Comment by SteveBraich** [comment]
Like which SideMenuItem gets loaded when you visit the page with the easy_sidemenu.

**Comment by Jamalianpour** [comment]
Use SideMenuController :
```dart
SideMenuController sideMenu = SideMenuController();

...

sideMenu.changePage(index);
```
