### ISSUE TITLE
open / close drawer

### ISSUE THREAD

**Issue by pselvaraj-uas** [Jamalianpour/easy_sidemenu#7]
Is there way to set the drawer to open by default and then animate to compact mode when I press a button?

**Comment by Jamalianpour** [comment]
Hello, you can do somethings like this:
```dart
SideMenuDisplayMode displayMode = SideMenuDisplayMode.open;

...

SideMenu(
  controller: page,
  items: items,
  style: SideMenuStyle(
  displayMode: displayMode,
  ),
 ),

...

IconButton(
  onPressed: () {
    setState(() {
      if (displayMode == SideMenuDisplayMode.open) {
        displayMode = SideMenuDisplayMode.compact;
      } else {
        displayMode = SideMenuDisplayMode.open;
      }
    });
  },
  icon: Icon(Icons.close),
),
```

**Comment by mt633** [comment]
Would be nice to have a toggle button within the library to expand/collapse the menu. Any plans on adding this?

Maybe something like this 
![](http://1.bp.blogspot.com/-zZRS5R3TS9M/U1kPwWoAKlI/AAAAAAAACWY/VvlM4AdVsuM/s1600/ExpandCollapse2.png)

or like this
![](https://sens.jse.co.za/WebHelp/WebHelpEU/sf_-_collapse_main_menu.png)

**Comment by Jamalianpour** [comment]
@mt633 Yes, I will add this to the library in the next version.
