### ISSUE TITLE
Mode

### ISSUE THREAD

**Issue by MauroGentile** [Jamalianpour/easy_sidemenu#72]
I need to have a State variable synched with Display mode.

I tried the following

```
 SideMenu(
            onDisplayModeChanged: (mode) {
              if (mode.name == 'compact') {
                setState(() {
                  tokenText = '';
                });
              } else {
                setState(() {
                  tokenText = 'Tokens';
                });
                ;
              }
            },
```

but throws the error:

The widget on which setState() or markNeedsBuild() was called was:
LoggedPage The widget which was currently being built when the offending call was made was:
KeyedSubtree-[GlobalKey#1a986]

How can I fix this?

**Comment by rekire** [comment]
This is a very common error. That means basically that the tree is currently been rendered so this is a bad timing for that call. You can use [`Future.delayed(...)`](https://api.flutter.dev/flutter/dart-async/Future/Future.delayed.html). However this will result that you have one renderer pass with the wrong content
