### ISSUE TITLE
bug #31 followup "side menu not showing after logout"

### ISSUE THREAD

**Issue by MauroGentile** [Jamalianpour/easy_sidemenu#73]
I do have the same problem as in bug #31.  I have implemented the suggested workaround and indeed the sidebar is now displayed also after the logout/login. However, in my case now I cannot see the item labels. I only can see the icons.

Do you plan to insert a solution in future releases? Do you have a resolution expected date?

Thank you

**Comment by aditya113141** [comment]
Hey, you can clone package from [here](https://github.com/aditya113141/easy_sidemenu_megsoft_version) and try. I believe it got solved after my PRs. Let me know if any issue is present.

**Comment by bollons** [comment]
> I do have the same problem as in bug #31. I have implemented the suggested workaround and indeed the sidebar is now displayed also after the logout/login. However, in my case now I cannot see the item labels. I only can see the icons.
> 
> Do you plan to insert a solution in future releases? Do you have a resolution expected date?
> 
> Thank you

same error at my side

**Comment by bollons** [comment]
> Hey, you can clone package from [here](https://github.com/aditya113141/easy_sidemenu) and try. I believe it got solved after my PRs. Let me know if any issue is present.

Hi Aditya, the link to github is missing (erroro 404). Can you plese provide the right one?
THanks

**Comment by aditya113141** [comment]
I updated the link

**Comment by bollons** [comment]
> I updated the link

It worked for a while and now is missing again

**Comment by aditya113141** [comment]
Can you share your code and how to reproduce the error ?

**Comment by bollons** [comment]
> Can you share your code and how to reproduce the error ?

Hi Aditya,
I've cloned the source you've put in github and now it works fine.
Thanks so much for your support.
When do you think you'll upload to pub.dev?

Thanks

**Comment by aditya113141** [comment]
Great. I misunderstood that you are having issue with the package.
Regarding the next release, I am not the owner. Ask @Jamalianpour
