### ISSUE TITLE
Open another widget from same widget by jumping

### ISSUE THREAD

**Issue by dshrinath** [Jamalianpour/easy_sidemenu#9]
First of all thank you so much for such easy package.

Issue:-

How can we keep this Side menu fixed for overall flutter app screens/widget?

E.g:- screen is divided into 2 parts, so I just wanted to load another new file/widget onto detailed view(right side part) from another dart file.

Settings page is loaded and then if about us page is linked within settings page and if we want to internal jumping, then instead of split view, it is opening into new widget (fullscreen), sidemenu is not able to fixed.

Easy side menu is decalared in home.dart file with pagecontrollor , but now I want to access and open new file which displayed as internal link and jumps to another dart file.
While jumping or opening, sidemenu is removed and full screen of widget is displayed. 

Expected results:- it should open new widget (from another file) and also side menu needs to fixed

Please help me out, how can I use this or fix this.

**Comment by Jamalianpour** [comment]
Hello @dshrinath 
You can do this in different ways, like these 2 ways :

- You can do that without navigator and just use `PageView` and pass widget to children from any other dart file. (This is good for desktop platforms)
```dart
PageController page = PageController();
Row(
  mainAxisAlignment: MainAxisAlignment.start,
  children: [
    SideMenu(
      controller: page,
      items: items,
    ),
    Expanded(
      child: PageView(
        controller: page,
        children: [
          PageOne(),
          PageTwo(),
          ...
        ],
      ),
    ),
  ],
),
```
- But if you want to use navigation use the `Navigator` widget, for more information on it, read the official document of `Navigator` [here](https://api.flutter.dev/flutter/widgets/Navigator-class.html) or see this answer https://stackoverflow.com/a/46503109/6796260
This medium blog can help you too https://medium.com/coding-with-flutter/flutter-case-study-multiple-navigators-with-bottomnavigationbar-90eb6caa6dbf
